#!/bin/bash

#if test -f "$1"
#then
#	if test -r "$1"
#	then
#		if test -w "$1"
#		then
#			echo "File $1 is an ordinary file and both readable and writable"
#		fi
#	fi	
#fi
#if test -x "$1"
#then
#	echo "File $1 is also executable."
#fi


# Listing 1
#if test -f "$1" && test -r "$1" && test -w "$1" && test -x "$1"
#then
#	echo "The file $1 is an ordinary file with readable, writeable and executable permissions."
#fi

if [ -d "$1" ]
then
	echo "File $1 is a directory"
fi

# Alternative to writing the code in Listing 1
if [ -f "$1" -a -r "$1" -a -w "$1" -a -x "$1" ] # The -a option functions as the Logical AND
then
	echo "The file $1 is an ordinary file with readable, writeable and executable permissions."
fi
