#!/bin/bash

#####################################################################
#               Standard error redirection
#####################################################################

#the new method
ls -lsh fumble.txt &> error.txt
