#!/bin/bash

###################################################################
#	Appending details to a file
###################################################################

echo "This file contains details of the file /etc/passwd" >> passwd.txt
echo $(cat /etc/passwd) >> passwd.txt
