#!/bin/bash

###########################################################
#	Pipelining using tee command
###########################################################

ls -ltr * | tee list_file.txt|grep -i HI 
