#!/bin/bash

#######################################################################
#               Displaying duplicated files using uniq
#######################################################################

# The uniq command only functions with sorted input

mkdir dir1 dir2
touch dir1/{A..C}-{1..5} dir2/{A..C}-{4..5}
ls -la dir1 dir2 | sort | uniq -d > duplicates.txt
